<?php include 'header.php' ?>

<div class="tucupampam" style="z-index: 100;"><h3 style="margin-top: 10px;">Disclaimer</h3> <p>Updated at 2021-04-21</p> <p class="p4"><span class="s1"><a>Enigma Helps</a> hereby grants you access to <a>.</a> (“the Website”) and invites you to purchase the services offered here.</span></p> <p class="p6"><br></p> <h3>Definitions and key terms</h3> <p class="p8"><span class="s1">To help explain things as clearly as possible in this Disclaimer,
 every time any of these terms are referenced,
 are strictly defined as:</span></p> <p class="p9"><br></p> <ul class="ul1"><li class="li8"><span class="s1"><strong>Cookie:</strong> small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
 provide analytics,
 remember information about you such as your language preference or login information.<br></span></li> <!----> <li class="li8"><span class="s1"><strong>Company:</strong> when this policy mentions “Company,
” “we,
” “us,
” or “our,
” it refers to <a>Enigma Helps</a> that is responsible for your information under this Privacy Policy.<br></span></li> <li class="li8"><span class="s1"><strong>Country:</strong> where <a>Enigma Helps</a> or the owners/founders of <a>Enigma Helps</a> are based,
 in this case is <a>INDIA</a>.<br></span></li> <li class="li8"><span class="s1"><strong>Customer:</strong> refers to the company,
 organization or person that signs up to use the <a>Enigma Helps</a> Service to manage the relationships with your consumers or service users.<br></span></li> <li class="li8"><span class="s1"><strong>Device:</strong> any internet connected device such as a phone,
 tablet,
 computer or any other device that can be used to visit <a>Enigma Helps</a> and use the services.<br></span></li> <li class="li8"><span class="s1"><strong>IP address:</strong> Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.<br></span></li> <li class="li8"><span class="s1"><strong>Personnel:</strong> refers to those individuals who are employed by <a>Enigma Helps</a> or are under contract to perform a service on behalf of one of the parties.<br></span></li> <li class="li8"><span class="s1"><strong>Personal Data:</strong> any information that directly,
 indirectly,
 or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.<br></span></li> <li class="li8"><span class="s1"><strong>Service:</strong> refers to the service provided by <a>Enigma Helps</a> as described in the relative terms (if available) and on this platform.<br></span></li> <li class="li8"><span class="s1"><strong>Third-party service:</strong> refers to advertisers,
 contest sponsors,
 promotional and marketing partners,
 and others who provide our content or whose products or services we think may interest you.<br></span></li> <li class="li8"><span class="s1"><strong>Website:</strong> <a>Enigma Helps</a>’s site,
 which can be accessed via this URL: <a>https://enigmahelps.com/.</a><br></span></li> <li class="li8"><span class="s1"><strong>You:</strong> a person or entity that is registered with <a>Enigma Helps</a> to use the Services.<br></span></li></ul> <p class="p3"><br></p> <h3>Limited liability</h3> <p class="p10"><span class="s1">
            We endeavour to update and/or supplement the content of our service on a regular basis. Despite our care and attention,
 content may be incomplete and/or incorrect.
            <br><br>
            The materials we offer are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from us.
            <br><br>
            Particularly,
 all prices on our service are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.
            <br><br>
            We shall not bear any liability for hyperlinks to websites or services of third parties included on our service. From our service,
 you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites,
 we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.
            <br><br>
            Please be also aware that when you leave our service,
 other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of
            these sites as well as their "Terms of Service" before engaging in any business or uploading any information.</span></p> <p class="p3"><br></p> <!----> <!----> <!----> <h3>Errors and Omissions Disclaimer</h3> <p class="p10"><span class="s1">We are not responsible for any content,
 code or any other imprecision.
                <br><br>
            We do not provide warranties or guarantees.
            <br><br>
            In no event shall we be liable for any special,
 direct,
 indirect,
 consequential,
 or incidental damages or any damages whatsoever,
 whether in an action of contract,
 negligence or other tort,
 arising out of or in connection with the use of the Service or the contents of the Service. We reserve the right to make additions,
 deletions,
 or modifications to the contents on the Service at any time without prior notice.</span></p> <p class="p3"><br></p> <h3>Copyright Disclaimer</h3> <p class="p10"><span class="s1">All intellectual property rights concerning these materials are vested in <a>Enigma Helps</a>. Copying,
 distribution and any other use of these materials is not permitted without the written permission from <a>Enigma Helps</a>,
 except and only to the extent otherwise provided in regulations of mandatory law (such as the right to quote),
 unless otherwise stated for certain materials.
            </span></p> <p class="p3"><br></p> <h3>General Disclaimer</h3> <p class="p10"><span class="s1">The <a>Enigma Helps</a> Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind,
 whether express or implied. <a>Enigma Helps</a> is a distributor and not a publisher of the content supplied by third parties; as such,
 <a>Enigma Helps</a> exercises no editorial control over such content and makes no warranty or representation as to the accuracy,
 reliability or currency of any information,
 content,
 service or merchandise provided through or accessible via the <a>Enigma Helps</a> Service. Without limiting the foregoing,
 <a>Enigma Helps</a> specifically disclaims all warranties and representations in any content transmitted on or in
            connection with the <a>Enigma Helps</a> Service or on sites that may appear as links on the <a>Enigma Helps</a> Service,
 or in the products provided as a part of,
 or otherwise in connection with,
 the <a>Enigma Helps</a> Service,
 including without limitation any warranties of merchantability,
 fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by <a>Enigma Helps</a> or any of its affiliates,
 employees,
 officers,
 directors,
 agents,
 or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing,
 <a>Enigma Helps</a> does not warrant that the <a>Enigma Helps</a> Service will be uninterrupted,
 uncorrupted,
 timely,
 or error-free.
            </span></p> <p class="p3"><br></p> <h3>Affiliate Disclosure</h3> <p class="p10"><span class="s1"><a>Enigma Helps</a> has affiliate links and in this section of the Disclaimer we will address how we use those affiliate links from other websites/ companies and products. These “affiliate links” are specific URLs that contain the affiliate's ID or username.</span></p> <p class="p10"><span class="s1">In compliance with the FTC guidelines, please assume the following about links and posts on this site:</span></p> <li class="li16"><span class="s3">Any/all of the links on <a>Enigma Helps</a> are affiliate links of which we receive a small commission from sales of certain items, but the price is the same for you. As <a>Enigma Helps</a> has grown, so have costs associated with running and maintaining it, and affiliate links are a way we help offset these costs.</span></li> <li class="li16"><span class="s3">If we post an affiliate link to a product, it is something that we personally use, support and would recommend without an affiliate link.</span></li> <li class="li16"><span class="s3">Unless otherwise noted, all reviews are of items we have purchased and we are not paid or compensated in any way.</span></li> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <p class="p3"><br></p> <h3>Health Disclosure</h3> <p class="p10"><span class="s1">The information on this service such as text, graphics, images, and other materials created by <a>Enigma Helps</a> or obtained from <a>Enigma Helps</a>’s licensors, and other materials contained on <a>Enigma Helps</a> (collectively, “content”) is intended solely for informational purposes and may not be used as a substitute for professional advice and/or information, as circumstances will vary from person to person. You should not act or rely upon this information without seeking professional advice. Do not attempt any of the suggested actions, solutions, remedies, or instructions found on this service without first consulting with a qualified professional. The materials are not intended to be nor do they constitute actionable professional advice. Transmissions of this information is not intended to create a professional-client relationship between Level Up Enterprises and you. The owners, editors, contributors, administrators, and other staff of Level Up Enterprises are not qualifies professionals, and are simply aggregating information found online for informational purposes only.
            <br><br>
            If you think you may have a medical emergency, call your doctor or 911 immediately. We do not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on this service. Reliance on any information provided by <a>Enigma Helps</a>, our employees, others appearing on the service at the invitation of <a>Enigma Helps</a>, or other visitors to the service is solely at your own risk.
            </span></p> <p class="p3"><br></p> <h3>Fitness Disclosure</h3> <p class="p10"><span class="s1">Please read this Fitness disclosure before applying any of the information on the .
              <br><br>
            We show information about Fitness and Nutritional advice. The information on this service such as text, graphics, images, and other materials created by <a>Enigma Helps</a> or obtained from <a>Enigma Helps</a>’s licensors, and other materials contained on <a>Enigma Helps</a> (collectively, “content”) is intended solely for informational purposes and may not be used as a substitute for professional advice and/or information, as circumstances will vary from person to person. You should not act or rely upon this information without seeking professional advice. Do not attempt any of the suggested actions, solutions, remedies, or instructions found on this service without first consulting with a qualified professional. The materials are not intended to be nor do they constitute actionable professional advice. If you use any of the information that we provide is at your own risk.
            Regular exercise is not always without risk, even for healthy individuals. Certain types of exercise are riskier thank others and all exercise is risky for some individuals.
            <br><br>
            It’s the same with diet. Some dietary recommendations are healthy for the majority of people but potentially dangerous to others.
            <br><br>
            You are responsible for your own health and safety at all times. As such, by visiting and using this service you acknowledge and agree that you have been assessed by a qualified medical professional (i.e your doctor) who has given you consent to take part in physical activity.
            <br><br>
            The exercises provided by <a>Enigma Helps</a> are for educational and entertainment purposes only, and is not to be interpreted as a recommendation for a specific treatment plan, product, or course of action. Exercise is not without risks, and this or any other exercise program may result in injury. They include but are not limited to: risk of injury, aggravation of a pre-existing condition, or adverse effect or over-exertion such as muscle strain, abnormal blood pressure, fainting, disorders of heartbeat, and very rare instances of heart attack. To reduce the risk of injury, before beginning this or any exercise program, please consult a healthcare provider for appropriate exercise prescription and safety precautions. The exercise instruction and advice presented are in no way intended as a substitute for medical consultation. We disclaim any liability from and in connection with this program. As with any exercise program, if at any point during your workout you begin to feel faint, dizzy, or have physical discomfort, you should stop immediately and consult a physician.
            </span></p> <p class="p3"><br></p> <!----> <!----> <!----> <!----> <!----> <!----> <h3>Educational Disclosure</h3> <p class="p10"><span class="s1">Any Information provided by <a>Enigma Helps</a> is for educational purposes only, and is not to be interpreted as a recommendation for
            a specific treatment plan, product, or course of action. We are a distributor and not a publisher of the content supplied by third parties; as such, We exercise no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information or educational content provided through or accessible via <a>Enigma Helps</a>. Without limiting the foregoing, We specifically disclaim all warranties and representations in any content transmitted on or in connection with us or on sites that may appear as links on our platform, or in the products provided as a part of, or otherwise in connection with us. No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty.
            </span></p> <p class="p3"><br></p> <h3>Advertising Disclosure</h3> <p class="p10"><span class="s1">This service may contain third party advertisements and links to third party sites. We do not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.
            Advertising keeps us and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.
            <br><br>
            Third party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by us of the third party sites, goods or services. We take no responsibility for the content of any of the ads, promises made, or the quality/reliability of the products or services offered in all advertisements.
            </span></p> <p class="p3"><br></p> <!----> <!----> <!----> <h3>Your Consent</h3> <p class="p10"><span class="s1">We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.</span></p> <p class="p3"><br></p> <h3>Changes To Our Disclaimer</h3> <p class="p10"><span class="s1">Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.</span></p> <p class="p3"><br></p> <h3>Contact Us</h3> <p class="p10"><span class="s1">Don't hesitate to contact us if you have any questions.</span></p> <ul class="ul1"><li class="li16"><span class="s3">Via Email: <a>enigmatechanicalclub@gmail.com</a></span></li> <li class="li16"><span class="s3">Via Phone Number: <a>+917081543730</a></span></li> <li class="li16"><span class="s3">Via this Link: <a>https://enigmahelps.com/contactus.php</a></span></li> <!----></ul></div>


<?php include 'footer.php' ?>